---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-db-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-db-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==          # "root" in base64
  SPRING_DATASOURCE_PASSWORD: cm9vdHBhc3N3b3Jk  # "rootpassword" in base64
